apiVersion: v1alpha1
kind: Infrastructure
metadata:
  name: signoz
spec:
  deployment:
    platform: aws
    mode: kubernetes
    flavor: terraform
  resource:
    kind: Installation
    spec:
      name: signoz
