apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: collector-deployment
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-collector-deployment
  name: signoz-collector-deployment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: signoz-collector-deployment
subjects:
- kind: ServiceAccount
  name: signoz-collector-deployment
  namespace: signoz
