name: signoz
services:
  collector-agent:
    command:
    - --config=/etc/collector/agent/agent.yaml
    deploy:
      replicas: 1
    environment:
      OTEL_COLLECTOR_ROLE: agent
    image: otel/opentelemetry-collector-contrib:0.139.0
    network_mode: host
    restart: unless-stopped
    user: "0:0"
    volumes:
    - ./collector/agent/agent.yaml:/etc/collector/agent/agent.yaml:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /:/hostfs:ro
