clickhouse:
  enabled: true
  fullnameOverride: signoz-telemetrystore-clickhouse
  image:
    repository: clickhouse/clickhouse-server
    tag: 25.12.5
  layout:
    replicasCount: 1
    shardsCount: 1
  zookeeper:
    enabled: true
    fullnameOverride: signoz-telemetrykeeper-zookeeper
    image:
      repository: signoz/zookeeper
      tag: 3.7.1
    replicaCount: 1
fullnameOverride: signoz
otelCollector:
  additionalEnvs:
    SIGNOZ_OTEL_COLLECTOR_TIMEOUT: 10m
  image:
    repository: signoz/signoz-otel-collector
    tag: latest
  name: ingester
  replicaCount: 1
postgresql:
  auth:
    database: signoz
    password: signoz
    username: signoz
  enabled: true
  fullnameOverride: signoz-metastore-postgres
  image:
    repository: postgres
    tag: "16"
signoz:
  image:
    repository: signoz/signoz
    tag: latest
  replicaCount: 1
telemetryStoreMigrator:
  name: signoz-telemetrystore-migrator
  timeout: 10m
