// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package signoz

type BaseConfig struct {
	Version struct {
		Banner struct {
			Enabled bool `json:"enabled"`
		} `json:"banner"`
	} `json:"version"`

	Instrumentation struct {
		Logs struct {
			Level string `json:"level"`
		} `json:"logs"`

		Traces struct {
			Enabled bool `json:"enabled"`

			Processors struct {
				Batch struct {
					Exporter struct {
						Otlp struct {
							Endpoint string `json:"endpoint"`
						} `json:"otlp"`
					} `json:"exporter"`
				} `json:"batch"`
			} `json:"processors"`
		} `json:"traces"`

		Metrics struct {
			Enabled bool `json:"enabled"`

			Readers struct {
				Pull struct {
					Exporter struct {
						Prometheus struct {
							Host string `json:"host"`

							Port int64 `json:"port"`
						} `json:"prometheus"`
					} `json:"exporter"`
				} `json:"pull"`
			} `json:"readers"`
		} `json:"metrics"`
	} `json:"instrumentation"`

	Web struct {
		Enabled bool `json:"enabled"`

		Prefix string `json:"prefix"`

		Directory string `json:"directory"`
	} `json:"web"`

	Cache struct {
		Provider string `json:"provider"`

		Memory struct {
			// ns
			Ttl int64 `json:"ttl"`

			Cleanup_interval string `json:"cleanup_interval"`
		} `json:"memory"`

		Redis struct {
			Host string `json:"host"`

			Port int64 `json:"port"`

			Password string `json:"password"`

			Db int64 `json:"db"`
		} `json:"redis"`
	} `json:"cache"`

	Sqlstore struct {
		Provider string `json:"provider"`

		Max_open_conns int64 `json:"max_open_conns"`

		Sqlite struct {
			Path string `json:"path"`

			Mode string `json:"mode"`

			Busy_timeout string `json:"busy_timeout"`
		} `json:"sqlite"`

		Postgres struct {
			Dsn string `json:"dsn"`
		} `json:"postgres"`
	} `json:"sqlstore"`

	Apiserver struct {
		Timeout struct {
			Default string `json:"default"`

			Max string `json:"max"`

			Excluded_routes []any/* CUE closed list */ `json:"excluded_routes"`
		} `json:"timeout"`

		Logging struct {
			Excluded_routes []any /* CUE closed list */ `json:"excluded_routes"`
		} `json:"logging"`
	} `json:"apiserver"`

	Querier struct {
		Cache_ttl string `json:"cache_ttl"`

		Flux_interval string `json:"flux_interval"`

		Max_concurrent_queries int64 `json:"max_concurrent_queries"`
	} `json:"querier"`

	Telemetrystore struct {
		Max_idle_conns int64 `json:"max_idle_conns"`

		Max_open_conns int64 `json:"max_open_conns"`

		Dial_timeout string `json:"dial_timeout"`

		Provider string `json:"provider"`

		Clickhouse struct {
			Dsn string `json:"dsn"`

			Cluster string `json:"cluster"`

			Settings struct {
				Max_execution_time int64 `json:"max_execution_time"`

				Max_execution_time_leaf int64 `json:"max_execution_time_leaf"`

				Timeout_before_checking_execution_speed int64 `json:"timeout_before_checking_execution_speed"`

				Max_bytes_to_read int64 `json:"max_bytes_to_read"`

				Max_result_rows int64 `json:"max_result_rows"`

				Ignore_data_skipping_indices string `json:"ignore_data_skipping_indices"`

				Secondary_indices_enable_bulk_filtering bool `json:"secondary_indices_enable_bulk_filtering"`
			} `json:"settings"`
		} `json:"clickhouse"`
	} `json:"telemetrystore"`

	Prometheus struct {
		Active_query_tracker struct {
			Enabled bool `json:"enabled"`

			Path string `json:"path"`

			Max_concurrent int64 `json:"max_concurrent"`
		} `json:"active_query_tracker"`
	} `json:"prometheus"`

	Alertmanager struct {
		Provider string `json:"provider"`

		Signoz struct {
			Poll_interval string `json:"poll_interval"`

			External_url string `json:"external_url"`

			Global struct {
				Resolve_timeout string `json:"resolve_timeout"`
			} `json:"global"`

			Route struct {
				Group_by []any/* CUE closed list */ `json:"group_by"`

				Group_interval string `json:"group_interval"`

				Group_wait string `json:"group_wait"`

				Repeat_interval string `json:"repeat_interval"`
			} `json:"route"`

			Alerts struct {
				Gc_interval string `json:"gc_interval"`
			} `json:"alerts"`

			Silences struct {
				Max int64 `json:"max"`

				Max_size_bytes int64 `json:"max_size_bytes"`

				Maintenance_interval string `json:"maintenance_interval"`

				Retention string `json:"retention"`
			} `json:"silences"`

			Nflog struct {
				Maintenance_interval string `json:"maintenance_interval"`

				Retention string `json:"retention"`
			} `json:"nflog"`
		} `json:"signoz"`
	} `json:"alertmanager"`

	Emailing struct {
		Enabled bool `json:"enabled"`

		Templates struct {
			Directory string `json:"directory"`
		} `json:"templates"`

		Smtp struct {
			Address string `json:"address"`

			From string `json:"from"`

			Hello string `json:"hello"`

			Headers map[string]any/* CUE top */ `json:"headers"`

			Auth struct {
				Username string `json:"username"`

				Password string `json:"password"`

				Secret string `json:"secret"`

				Identity string `json:"identity"`
			} `json:"auth"`

			Tls struct {
				Enabled bool `json:"enabled"`

				Insecure_skip_verify bool `json:"insecure_skip_verify"`

				Ca_file_path string `json:"ca_file_path"`

				Key_file_path string `json:"key_file_path"`

				Cert_file_path string `json:"cert_file_path"`
			} `json:"tls"`
		} `json:"smtp"`
	} `json:"emailing"`

	Sharder struct {
		Provider string `json:"provider"`

		Single struct {
			Org_id string `json:"org_id"`
		} `json:"single"`
	} `json:"sharder"`

	Analytics struct {
		Enabled bool `json:"enabled"`

		Segment struct {
			Key string `json:"key"`
		} `json:"segment"`
	} `json:"analytics"`

	Statsreporter struct {
		Enabled bool `json:"enabled"`

		Interval string `json:"interval"`

		Collect struct {
			Identities bool `json:"identities"`
		} `json:"collect"`
	} `json:"statsreporter"`

	Gateway struct {
		Url string `json:"url"`
	} `json:"gateway"`

	Tokenizer struct {
		Provider string `json:"provider"`

		Lifetime struct {
			Idle string `json:"idle"`

			Max string `json:"max"`
		} `json:"lifetime"`

		Rotation struct {
			Interval string `json:"interval"`

			Duration string `json:"duration"`
		} `json:"rotation"`

		Jwt struct {
			Secret string `json:"secret"`
		} `json:"jwt"`

		Opaque struct {
			Gc struct {
				Interval string `json:"interval"`
			} `json:"gc"`

			Token struct {
				Max_per_user int64 `json:"max_per_user"`
			} `json:"token"`
		} `json:"opaque"`
	} `json:"tokenizer"`
}

// Common enums
type LogLevel string

type CacheProvider string

type SQLStoreProvider string

type TelemetryProvider string

type AlertmanagerProvider string

type SharderProvider string

type TokenizerProvider string

// Go-style duration strings: 1s, 5m, 6h, 120h, etc.
type Duration string

type ConfigSpec struct {
	Version struct {
		Banner struct {
			Enabled bool `json:"enabled"`
		} `json:"banner"`
	} `json:"version"`

	Instrumentation struct {
		Logs struct {
			Level LogLevel `json:"level"`
		} `json:"logs"`

		Traces struct {
			Enabled bool `json:"enabled"`

			Processors struct {
				Batch struct {
					Exporter struct {
						Otlp struct {
							Endpoint string `json:"endpoint"`
						} `json:"otlp"`
					} `json:"exporter"`
				} `json:"batch"`
			} `json:"processors"`
		} `json:"traces"`

		Metrics struct {
			Enabled bool `json:"enabled"`

			Readers struct {
				Pull struct {
					Exporter struct {
						Prometheus struct {
							Host string `json:"host"`

							Port int64 `json:"port"`
						} `json:"prometheus"`
					} `json:"exporter"`
				} `json:"pull"`
			} `json:"readers"`
		} `json:"metrics"`
	} `json:"instrumentation"`

	Web struct {
		Enabled bool `json:"enabled"`

		Prefix string `json:"prefix"`

		Directory string `json:"directory"`
	} `json:"web"`

	Cache struct {
		Provider CacheProvider `json:"provider"`

		Memory struct {
			// ns
			Ttl int64 `json:"ttl"`

			Cleanup_interval Duration `json:"cleanup_interval"`
		} `json:"memory"`

		Redis struct {
			Host string `json:"host"`

			Port int64 `json:"port"`

			Password string `json:"password"`

			Db int64 `json:"db"`
		} `json:"redis"`
	} `json:"cache"`

	Sqlstore struct {
		Provider SQLStoreProvider `json:"provider"`

		Max_open_conns int64 `json:"max_open_conns"`

		Sqlite struct {
			Path string `json:"path"`

			Mode string `json:"mode"`

			Busy_timeout Duration `json:"busy_timeout"`
		} `json:"sqlite"`

		Postgres struct {
			Dsn string `json:"dsn"`
		} `json:"postgres"`
	} `json:"sqlstore"`

	Apiserver struct {
		Timeout struct {
			Default Duration `json:"default"`

			Max Duration `json:"max"`

			Excluded_routes []string `json:"excluded_routes"`
		} `json:"timeout"`

		Logging struct {
			Excluded_routes []string `json:"excluded_routes"`
		} `json:"logging"`
	} `json:"apiserver"`

	Querier struct {
		Cache_ttl Duration `json:"cache_ttl"`

		Flux_interval Duration `json:"flux_interval"`

		Max_concurrent_queries int64 `json:"max_concurrent_queries"`
	} `json:"querier"`

	Telemetrystore struct {
		Max_idle_conns int64 `json:"max_idle_conns"`

		Max_open_conns int64 `json:"max_open_conns"`

		Dial_timeout Duration `json:"dial_timeout"`

		Provider TelemetryProvider `json:"provider"`

		Clickhouse struct {
			Dsn string `json:"dsn"`

			Cluster string `json:"cluster"`

			Settings struct {
				Max_execution_time int64 `json:"max_execution_time"`

				Max_execution_time_leaf int64 `json:"max_execution_time_leaf"`

				Timeout_before_checking_execution_speed int64 `json:"timeout_before_checking_execution_speed"`

				Max_bytes_to_read int64 `json:"max_bytes_to_read"`

				Max_result_rows int64 `json:"max_result_rows"`

				Ignore_data_skipping_indices string `json:"ignore_data_skipping_indices"`

				Secondary_indices_enable_bulk_filtering bool `json:"secondary_indices_enable_bulk_filtering"`
			} `json:"settings"`
		} `json:"clickhouse"`
	} `json:"telemetrystore"`

	Prometheus struct {
		Active_query_tracker struct {
			Enabled bool `json:"enabled"`

			Path string `json:"path"`

			Max_concurrent int64 `json:"max_concurrent"`
		} `json:"active_query_tracker"`
	} `json:"prometheus"`

	Alertmanager struct {
		Provider AlertmanagerProvider `json:"provider"`

		Signoz struct {
			Poll_interval Duration `json:"poll_interval"`

			External_url string `json:"external_url"`

			Global struct {
				Resolve_timeout Duration `json:"resolve_timeout"`
			} `json:"global"`

			Route struct {
				Group_by []string `json:"group_by"`

				Group_interval Duration `json:"group_interval"`

				Group_wait Duration `json:"group_wait"`

				Repeat_interval Duration `json:"repeat_interval"`
			} `json:"route"`

			Alerts struct {
				Gc_interval Duration `json:"gc_interval"`
			} `json:"alerts"`

			Silences struct {
				Max int64 `json:"max"`

				Max_size_bytes int64 `json:"max_size_bytes"`

				Maintenance_interval Duration `json:"maintenance_interval"`

				Retention Duration `json:"retention"`
			} `json:"silences"`

			Nflog struct {
				Maintenance_interval Duration `json:"maintenance_interval"`

				Retention Duration `json:"retention"`
			} `json:"nflog"`
		} `json:"signoz"`
	} `json:"alertmanager"`

	Emailing struct {
		Enabled bool `json:"enabled"`

		Templates struct {
			Directory string `json:"directory"`
		} `json:"templates"`

		Smtp struct {
			Address string `json:"address"`

			From string `json:"from"`

			Hello string `json:"hello"`

			Headers map[string]any/* CUE top */ `json:"headers"`

			Auth struct {
				Username string `json:"username"`

				Password string `json:"password"`

				Secret string `json:"secret"`

				Identity string `json:"identity"`
			} `json:"auth"`

			Tls struct {
				Enabled bool `json:"enabled"`

				Insecure_skip_verify bool `json:"insecure_skip_verify"`

				Ca_file_path string `json:"ca_file_path"`

				Key_file_path string `json:"key_file_path"`

				Cert_file_path string `json:"cert_file_path"`
			} `json:"tls"`
		} `json:"smtp"`
	} `json:"emailing"`

	Sharder struct {
		Provider SharderProvider `json:"provider"`

		Single struct {
			Org_id string `json:"org_id"`
		} `json:"single"`
	} `json:"sharder"`

	Analytics struct {
		Enabled bool `json:"enabled"`

		Segment struct {
			Key string `json:"key"`
		} `json:"segment"`
	} `json:"analytics"`

	Statsreporter struct {
		Enabled bool `json:"enabled"`

		Interval Duration `json:"interval"`

		Collect struct {
			Identities bool `json:"identities"`
		} `json:"collect"`
	} `json:"statsreporter"`

	Gateway struct {
		Url string `json:"url"`
	} `json:"gateway"`

	Tokenizer struct {
		Provider TokenizerProvider `json:"provider"`

		Lifetime struct {
			Idle Duration `json:"idle"`

			Max Duration `json:"max"`
		} `json:"lifetime"`

		Rotation struct {
			Interval Duration `json:"interval"`

			Duration Duration `json:"duration"`
		} `json:"rotation"`

		Jwt struct {
			Secret string `json:"secret"`
		} `json:"jwt"`

		Opaque struct {
			Gc struct {
				Interval Duration `json:"interval"`
			} `json:"gc"`

			Token struct {
				Max_per_user int64 `json:"max_per_user"`
			} `json:"token"`
		} `json:"opaque"`
	} `json:"tokenizer"`
}
