apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: collector-deployment
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-collector-deployment
  name: signoz-collector-deployment
