apiVersion: v1alpha1
metadata:
  name: signoz
spec:
  deployment:
    flavor: helm
    mode: kubernetes
  telemetrystore:
    spec:
      config:
        knobs:
          resources:
            requests:
              memory: "8Gi"
              cpu: "2"
            limits:
              memory: "16Gi"
          tolerations:
            - key: "dedicated"
              operator: "Equal"
              value: "clickhouse"
              effect: "NoSchedule"
  ingester:
    spec:
      config:
        knobs:
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
          nodeSelector:
            workload: ingestion
patches:
  - path: patches/custom-values.yaml
