clickhouse:
  enabled: true
  image:
    repository: clickhouse/clickhouse-server
    tag: 25.5.6
  layout:
    replicasCount: 0
    shardsCount: 1
  nodeSelector:
    node-type: storage
  persistence:
    size: 100Gi
    storageClass: gp3
  resources:
    limits:
      cpu: "4"
      memory: 16Gi
    requests:
      cpu: "2"
      memory: 8Gi
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: clickhouse
otelCollector:
  enabled: true
  image:
    repository: signoz/signoz-otel-collector
    tag: latest
  podAnnotations:
    prometheus.io/port: "8888"
    prometheus.io/scrape: "true"
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
postgresql:
  auth:
    database: signoz
    password: signoz
    username: signoz
  enabled: true
  image:
    repository: postgres
    tag: 16
signoz:
  env:
    SIGNOZ_SQLSTORE_POSTGRES_DSN: postgres://signoz:signoz@signoz-metastore:5432/signoz?sslmode=disable
    SIGNOZ_SQLSTORE_PROVIDER: postgres
    SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN: tcp://signoz-clickhouse:9000
    SIGNOZ_TELEMETRYSTORE_PROVIDER: clickhouse
  image:
    repository: signoz/signoz
    tag: latest
  replicaCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    type: LoadBalancer
zookeeper:
  enabled: true
  image:
    repository: clickhouse/clickhouse-keeper
    tag: 25.5.6
  replicaCount: 1
