FROM clickhouse/clickhouse-server:{{ $.Spec.TelemetryStore.Spec.Version }}

COPY configs/config.yaml /etc/clickhouse-server/config.yaml
COPY configs/functions.yaml /etc/clickhouse-server/config.d/functions.yaml

RUN mkdir -p /var/lib/clickhouse/user_scripts/ \
    && chown clickhouse:clickhouse /var/lib/clickhouse/user_scripts

ARG VERSION=v0.0.1
ARG CLICKHOUSE_SKIP_USER_SETUP=1
RUN set -eux; \
    node_os=$(uname -s | tr '[:upper:]' '[:lower:]'); \
    node_arch=$(uname -m | sed 's/aarch64/arm64/' | sed 's/x86_64/amd64/'); \
    echo "Fetching histogram-quantile for ${node_os}/${node_arch}"; \
    cd /tmp; \
    wget -O histogram-quantile.tar.gz \
      "https://github.com/SigNoz/signoz/releases/download/histogram-quantile%2F${VERSION}/histogram-quantile_${node_os}_${node_arch}.tar.gz"; \
    tar -xvzf histogram-quantile.tar.gz; \
    mv histogram-quantile /var/lib/clickhouse/user_scripts/histogramQuantile; \
    rm histogram-quantile.tar.gz
