apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: signoz
resources:
- namespace.yaml
- clickhouseinstallations.clickhouse.altinity.com.crd.yaml
- clickhouseinstallationtemplates.clickhouse.altinity.com.crd.yaml
- clickhouseoperatorconfigurations.clickhouse.altinity.com.crd.yaml
- clickhousekeeperinstallations.clickhouse-keeper.altinity.com.crd.yaml
- serviceaccount.yaml
- configmap.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- service.yaml
- deployment.yaml
