// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package signozotelcollector

// Common Types
type Endpoint string

type TLSConfig struct {
	Cert_file string `json:"cert_file,omitempty"`

	Key_file string `json:"key_file,omitempty"`

	Ca_file string `json:"ca_file,omitempty"`

	Insecure bool `json:"insecure,omitempty"`
}

// OTLP Receiver
type GRPCProtocol struct {
	Endpoint Endpoint `json:"endpoint,omitempty"`

	Transport string `json:"transport,omitempty"`

	Max_recv_msg_size_mib int64 `json:"max_recv_msg_size_mib,omitempty"`

	Max_concurrent_streams int64 `json:"max_concurrent_streams,omitempty"`

	Tls TLSConfig `json:"tls,omitempty"`
}

type HTTPProtocol struct {
	Endpoint Endpoint `json:"endpoint,omitempty"`

	Max_request_body_size int64 `json:"max_request_body_size,omitempty"`

	Tls TLSConfig `json:"tls,omitempty"`
}

type OTLPReceiver struct {
	Protocols struct {
		Grpc GRPCProtocol `json:"grpc,omitempty"`

		Http HTTPProtocol `json:"http,omitempty"`
	} `json:"protocols,omitempty"`
}

// Prometheus Receiver
type ScrapeConfig struct {
	Job_name string `json:"job_name"`

	Scrape_interval string `json:"scrape_interval,omitempty"`

	Static_configs []struct {
		Targets []string `json:"targets"`

		Labels map[string]string `json:"labels,omitempty"`
	} `json:"static_configs,omitempty"`
}

type PrometheusReceiver struct {
	Config struct {
		Global struct {
			Scrape_interval string `json:"scrape_interval,omitempty"`
		} `json:"global,omitempty"`

		Scrape_configs []ScrapeConfig `json:"scrape_configs,omitempty"`
	} `json:"config,omitempty"`
}

// Top-level Sections
type Receivers map[string]map[string]any /* CUE top */

type Processors map[string]map[string]any /* CUE top */

type Exporters map[string]map[string]any /* CUE top */

type Extensions map[string]map[string]any /* CUE top */

type Connectors map[string]map[string]any /* CUE top */

type Pipeline struct {
	Receivers []string `json:"receivers,omitempty"`

	Processors []string `json:"processors,omitempty"`

	Exporters []string `json:"exporters,omitempty"`
}

type Pipelines map[string]Pipeline

type Service struct {
	Telemetry struct {
		Logs struct {
			Encoding string `json:"encoding,omitempty"`
		} `json:"logs,omitempty"`
	} `json:"telemetry,omitempty"`

	Extensions []string `json:"extensions,omitempty"`

	Pipelines Pipelines `json:"pipelines,omitempty"`
}

type ConfigSpec struct {
	Connectors Connectors `json:"connectors,omitempty"`

	Receivers Receivers `json:"receivers,omitempty"`

	Processors Processors `json:"processors,omitempty"`

	Exporters Exporters `json:"exporters,omitempty"`

	Extensions Extensions `json:"extensions,omitempty"`

	Service Service `json:"service,omitempty"`
}

type BaseConfig struct {
	Connectors map[string]map[string]any/* CUE top */ `json:"connectors"`

	Receivers map[string]map[string]any/* CUE top */ `json:"receivers"`

	Processors map[string]map[string]any/* CUE top */ `json:"processors"`

	Exporters map[string]map[string]any/* CUE top */ `json:"exporters"`

	Extensions map[string]map[string]any/* CUE top */ `json:"extensions"`

	Service struct {
		Telemetry struct {
			Logs struct {
				Encoding string `json:"encoding"`
			} `json:"logs"`
		} `json:"telemetry"`

		Extensions []any/* CUE closed list */ `json:"extensions"`

		Pipelines map[string]Pipeline `json:"pipelines"`
	} `json:"service"`
}
