[Service]
Environment=OTEL_COLLECTOR_ROLE=agent
Environment=SIGNOZ_INGESTION_ENDPOINT=http://<signoz-host>:4318

[X-Foundry]
Owner=foundry.signoz.io/kind=CollectionAgent,foundry.signoz.io/managed-by=foundry,foundry.signoz.io/name=signoz
