apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: signoz-telemetrystore
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telemetrystore
      app.kubernetes.io/instance: signoz
