apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: false
  includeTemplates: true
  pairs:
    foundry.signoz.io/kind: CollectionAgent
    foundry.signoz.io/managed-by: foundry
    foundry.signoz.io/name: signoz
namespace: signoz
resources:
- namespace.yaml
- collector/agent
