apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - agent.yaml
  name: signoz-collector-agent
kind: Kustomization
resources:
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- service.yaml
- workload.yaml
