apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: collector-agent
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-collector-agent
  name: signoz-collector-agent
