// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package casting

import (
	clickhouseConfig "github.com/signoz/foundry/internal/schema/molding/clickhouse"
	signozConfig "github.com/signoz/foundry/internal/schema/molding/signoz"
	signozOtelCollectorConfig "github.com/signoz/foundry/internal/schema/molding/signozotelcollector"
	zookeeperConfig "github.com/signoz/foundry/internal/schema/molding/zookeeper"
)

// Matches versions like v1, v2, v3
type SchemaVersion string

// Supported platform identifiers
type Platform string

// Generic component definition used when a component
// does not require any special fields.
type Component struct {
	Enabled bool `json:"enabled"`

	Replicas int64 `json:"replicas"`

	Version string `json:"version"`
}

// Known components that have special schemas.
// Components listed here override the generic component definition.
type ComponentRegistry struct {
	SignozOtelCollector struct {
		Config signozOtelCollectorConfig.BaseConfig `json:"config,omitempty"`

		Enabled bool `json:"enabled"`

		Replicas int64 `json:"replicas"`

		Version string `json:"version"`
	} `json:"signozOtelCollector"`

	Clickhouse struct {
		Config clickhouseConfig.BaseConfig `json:"config,omitempty"`

		Enabled bool `json:"enabled"`

		Replicas int64 `json:"replicas"`

		Version string `json:"version"`
	} `json:"clickhouse"`

	Signoz struct {
		Config signozConfig.BaseConfig `json:"config,omitempty"`

		Enabled bool `json:"enabled"`

		Replicas int64 `json:"replicas"`

		Version string `json:"version"`
	} `json:"signoz"`

	Zookeeper struct {
		Config zookeeperConfig.BaseConfig `json:"config,omitempty"`

		Enabled bool `json:"enabled"`

		Replicas int64 `json:"replicas"`

		Version string `json:"version"`
	} `json:"zookeeper"`
}

// Top-level configuration schema for a Foundry casting.
// Selects the appropriate component schema based on ID.
// Falls back to the generic component definition if not matched.
type Config struct {
	SchemaVersion SchemaVersion `json:"schemaVersion"`

	Platform Platform `json:"platform"`

	Components map[string]map[string]any `json:"components"`

	Requirements any/* TODO: IncompleteKind: _|_ */ `json:"requirements"`
}
