// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package clickhouse

// Commons helpers
type LoggerLevel string

type LoggerFormattingType string

type LoadBalancing string

type ConfigSpec struct {
	// File: config.yaml (main ClickHouse configuration)
	ServerConfig map[string]any/* CUE top */ `json:"serverConfig,omitempty"`

	// File: users.yaml (users, profiles, quotas)
	UsersConfig map[string]any/* CUE top */ `json:"usersConfig,omitempty"`

	CustomFunctionConfig map[string]any/* CUE top */ `json:"customFunctionConfig,omitempty"`

	// Additional config files in config.d/
	Config_d map[string]map[string]any/* CUE top */ `json:"config_d,omitempty"`

	// Optional: users.d/ directory
	Users_d map[string]map[string]any/* CUE top */ `json:"users_d,omitempty"`
}

type BaseConfig struct {
	// File: config.yaml (main ClickHouse configuration)
	ServerConfig map[string]any/* CUE top */ `json:"serverConfig"`

	// File: users.yaml (users, profiles, quotas)
	UsersConfig map[string]any/* CUE top */ `json:"usersConfig"`

	CustomFunctionConfig map[string]any/* CUE top */ `json:"customFunctionConfig"`

	// Additional config files in config.d/
	Config_d map[string]map[string]any/* CUE top */ `json:"config_d,omitempty"`

	// Optional: users.d/ directory
	Users_d map[string]map[string]any/* CUE top */ `json:"users_d,omitempty"`
}
