clickhouse:
  enabled: true
  image:
    repository: clickhouse/clickhouse-server
    tag: 25.5.6
  layout:
    replicasCount: 0
    shardsCount: 1
  serviceMonitor:
    enabled: true
    interval: 30s
otelCollector:
  enabled: true
  image:
    repository: signoz/signoz-otel-collector
    tag: latest
  replicaCount: 1
  serviceMonitor:
    enabled: true
    interval: 15s
postgresql:
  auth:
    database: signoz
    password: signoz
    username: signoz
  enabled: true
  image:
    repository: postgres
    tag: 16
signoz:
  env:
    SIGNOZ_SQLSTORE_POSTGRES_DSN: postgres://signoz:signoz@signoz-metastore:5432/signoz?sslmode=disable
    SIGNOZ_SQLSTORE_PROVIDER: postgres
    SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN: tcp://signoz-clickhouse:9000
    SIGNOZ_TELEMETRYSTORE_PROVIDER: clickhouse
  image:
    repository: signoz/signoz
    tag: latest
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    className: nginx
    enabled: true
    hosts:
    - host: signoz.example.com
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - signoz.example.com
      secretName: signoz-tls
  replicaCount: 1
zookeeper:
  enabled: true
  image:
    repository: clickhouse/clickhouse-keeper
    tag: 25.5.6
  replicaCount: 1
