apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - deployment.yaml=collector/deployment/deployment.yaml
  name: signoz-collector-deployment
kind: Kustomization
labels:
- includeSelectors: false
  includeTemplates: true
  pairs:
    foundry.signoz.io/kind: CollectionAgent
    foundry.signoz.io/managed-by: foundry
    foundry.signoz.io/name: signoz
namespace: signoz
resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- service.yaml
- deployment.yaml
