apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: signoz
resources:
- namespace.yaml
- telemetrystore/clickhouse-operator
- telemetrystore/clickhouse-instance
- telemetrykeeper
- telemetrystore-migrator
- metastore/postgresql
- signoz
- ingester
